package Formularios;

//import Beans.Sesion;
import Beans.MedicoBean;
import Beans.Sesion;
import Clases.MedicoAdministrador;
import UpperEssential.UpperEssentialLookAndFeel;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author David Pantaleón
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    Sesion s;
    MedicoAdministrador ma;
    MedicoBean m;
    private static final Logger logger = Logger.getLogger("MenuPrincipal");
    public MenuPrincipal(Sesion ps) {
        initComponents();
        s=ps;
        logger.info("Ced_prof:" + s.getCedulaProfMedico());
        if (ps.getRol().equals("Administrador")){
            ma=new MedicoAdministrador(s.getCedulaProfMedico());   
        }else{
            m=new MedicoBean(s.getCedulaProfMedico());
            ocultarComponentes();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        SubMenu1Medico = new javax.swing.JMenuItem();
        SubMenu2Medico = new javax.swing.JMenuItem();
        SubMenu3Medico = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SDSTPO V. 1.1");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setType(java.awt.Window.Type.POPUP);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1153, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        jMenu1.setText("Medico");

        SubMenu1Medico.setText("Nuevo Medico");
        SubMenu1Medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenu1MedicoActionPerformed(evt);
            }
        });
        jMenu1.add(SubMenu1Medico);

        SubMenu2Medico.setText("Actualizar Medico");
        SubMenu2Medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenu2MedicoActionPerformed(evt);
            }
        });
        jMenu1.add(SubMenu2Medico);

        SubMenu3Medico.setText("Consultar Medico");
        jMenu1.add(SubMenu3Medico);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Paciente");

        jMenuItem3.setText("Nuevo Paciente");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Consultar Paciente");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Medicamento");

        jMenuItem1.setText("Nuevo");
        jMenu4.add(jMenuItem1);

        jMenuItem2.setText("Consultar");
        jMenu4.add(jMenuItem2);

        jMenuItem6.setText("Editar");
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Sesion");

        jMenuItem5.setText("Cerrar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubMenu1MedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenu1MedicoActionPerformed
        // TODO add your handling code here:
        NuevoMedico nm=new NuevoMedico(ma);
        escritorio.add(nm);
        nm.show();
    }//GEN-LAST:event_SubMenu1MedicoActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        this.hide();
        inicioSesion is=new inicioSesion();
        is.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void SubMenu2MedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenu2MedicoActionPerformed
        //this.hide();
        ActualizarMedic am=new ActualizarMedic(ma);
        escritorio.add(am);
        am.show();
    }//GEN-LAST:event_SubMenu2MedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            UIManager.setLookAndFeel(new UpperEssentialLookAndFeel("C:\\Users\\David Pantaleón\\Downloads\\LibreriaUpperEssential\\Librerias\\Checo.theme"));
        }catch (UnsupportedLookAndFeelException e )
        {
            
        }
        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem SubMenu1Medico;
    private javax.swing.JMenuItem SubMenu2Medico;
    private javax.swing.JMenuItem SubMenu3Medico;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    // End of variables declaration//GEN-END:variables

    private void ocultarComponentes() {
        SubMenu1Medico.setVisible(false);
        SubMenu2Medico.setVisible(false);
    }
}
