/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.MedicoAdministrador;
import Imagenes.imagenes;
import datechooser.model.exeptions.IncompatibleDataExeption;
import java.net.URL;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author laloe
 */
public class NuevoMedico extends javax.swing.JDialog {

    /**
     * Creates new form NuevoMedico
     */
     MedicoAdministrador med_adm;
    String nombre,apeP,apeM,dir,espe,tel,usuario,password,sexo;
    String f_nac,admin;//=new Date(1,1,1900);
    int cedula_prof;
    public NuevoMedico(java.awt.Frame parent, boolean modal,MedicoAdministrador me_ad) {
        super(parent, modal);
        initComponents();
        limpiarLeyendasError();
        med_adm=me_ad;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        BtnLimpiar = new javax.swing.JButton();
        jtf_tel = new javax.swing.JTextField();
        le_nombre = new javax.swing.JLabel();
        jtf_dir = new javax.swing.JTextField();
        le_apep = new javax.swing.JLabel();
        le_apem = new javax.swing.JLabel();
        BtnGuardar = new javax.swing.JButton();
        le_telefono = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        le_cedPro = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lo_nombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lo_apep = new javax.swing.JLabel();
        lo_cedPro = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lo_pas = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lo_usu = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtf_nombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtf_pass = new javax.swing.JTextField();
        jtf_apep = new javax.swing.JTextField();
        jtf_usu = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtf_apem = new javax.swing.JTextField();
        jtf_cedPro = new javax.swing.JTextField();
        dateCombo = new datechooser.beans.DateChooserCombo();
        comboSexo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        comboAdmin = new javax.swing.JComboBox<>();
        comboEspe = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SDSTPO v1.1 - Medico");

        jLabel12.setText("Password");

        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        jtf_tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_telKeyPressed(evt);
            }
        });

        le_nombre.setForeground(new java.awt.Color(255, 0, 0));
        le_nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        le_nombre.setText("Solo acepta carateres validos (A-Z)");

        le_apep.setForeground(new java.awt.Color(255, 0, 0));
        le_apep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        le_apep.setText("Solo acepta carateres validos (A-Z)");

        le_apem.setForeground(new java.awt.Color(255, 0, 0));
        le_apem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        le_apem.setText("Solo acepta carateres validos (A-Z)");

        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        le_telefono.setForeground(new java.awt.Color(255, 0, 0));
        le_telefono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        le_telefono.setText("Solo números");

        Titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Titulo.setText("Registrar Medico");

        le_cedPro.setForeground(new java.awt.Color(255, 0, 0));
        le_cedPro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        le_cedPro.setText("Solo números");

        jLabel2.setText("Nombre");

        lo_nombre.setForeground(new java.awt.Color(255, 0, 0));
        lo_nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lo_nombre.setText("*");

        jLabel3.setText("Apellido Paterno");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Apellido Materno");

        lo_apep.setForeground(new java.awt.Color(255, 0, 0));
        lo_apep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lo_apep.setText("*");

        lo_cedPro.setForeground(new java.awt.Color(255, 0, 0));
        lo_cedPro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lo_cedPro.setText("*");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Fecha Nacimiento");

        lo_pas.setForeground(new java.awt.Color(255, 0, 0));
        lo_pas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lo_pas.setText("*");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Telefono");

        lo_usu.setForeground(new java.awt.Color(255, 0, 0));
        lo_usu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lo_usu.setText("*");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Dirección");

        jLabel8.setText("Sexo");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Especialidad");

        jtf_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_nombreKeyPressed(evt);
            }
        });

        jLabel10.setText("Cedula Profesional");

        jtf_apep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_apepKeyPressed(evt);
            }
        });

        jLabel11.setText("Usuario");

        jtf_apem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_apemKeyPressed(evt);
            }
        });

        jtf_cedPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_cedProKeyPressed(evt);
            }
        });

        dateCombo.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dateCombo.setFormat(2);
    try {
        dateCombo.setDefaultPeriods(new datechooser.model.multiple.PeriodSet(new datechooser.model.multiple.Period(new java.util.GregorianCalendar(2016, 9, 8),
            new java.util.GregorianCalendar(2016, 9, 8))));
} catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
    e1.printStackTrace();
    }

    comboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MASCULINO", "FEMENINO" }));

    jLabel1.setText("Administrador");

    comboAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "SI" }));

    comboEspe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OPTOMETRISTA", "OFTÁLMOLOGO" }));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(355, 355, 355)
            .addComponent(Titulo))
        .addGroup(layout.createSequentialGroup()
            .addGap(69, 69, 69)
            .addComponent(le_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(114, 114, 114)
            .addComponent(le_apep, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(113, 113, 113)
            .addComponent(le_apem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(layout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addComponent(lo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(6, 6, 6)
            .addComponent(jLabel2)
            .addGap(6, 6, 6)
            .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(lo_apep)
            .addGap(6, 6, 6)
            .addComponent(jLabel3)
            .addGap(6, 6, 6)
            .addComponent(jtf_apep, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(27, 27, 27)
            .addComponent(jLabel4)
            .addGap(6, 6, 6)
            .addComponent(jtf_apem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(layout.createSequentialGroup()
            .addGap(383, 383, 383)
            .addComponent(le_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(layout.createSequentialGroup()
            .addGap(26, 26, 26)
            .addComponent(jLabel5)
            .addGap(4, 4, 4)
            .addComponent(dateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(38, 38, 38)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(6, 6, 6)
            .addComponent(jtf_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(27, 27, 27)
            .addComponent(jLabel8)
            .addGap(4, 4, 4)
            .addComponent(comboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(layout.createSequentialGroup()
            .addGap(26, 26, 26)
            .addComponent(jLabel7)
            .addGap(4, 4, 4)
            .addComponent(jtf_dir, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(layout.createSequentialGroup()
            .addGap(595, 595, 595)
            .addComponent(le_cedPro, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(layout.createSequentialGroup()
            .addGap(250, 250, 250)
            .addComponent(BtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(225, 225, 225)
            .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(layout.createSequentialGroup()
            .addGap(26, 26, 26)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel9)
                    .addGap(18, 18, 18)
                    .addComponent(comboEspe, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(lo_usu)
                    .addGap(6, 6, 6)
                    .addComponent(jLabel11)
                    .addGap(4, 4, 4)
                    .addComponent(jtf_usu, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(45, 45, 45)
                    .addComponent(lo_pas)
                    .addGap(6, 6, 6)
                    .addComponent(jLabel12)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addComponent(jtf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(64, 64, 64)
                    .addComponent(jLabel1)
                    .addGap(6, 6, 6)
                    .addComponent(comboAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(129, 129, 129)
                    .addComponent(lo_cedPro)
                    .addGap(6, 6, 6)
                    .addComponent(jLabel10)
                    .addGap(11, 11, 11)
                    .addComponent(jtf_cedPro, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(11, 11, 11)
            .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(le_nombre)
                .addComponent(le_apep)
                .addComponent(le_apem))
            .addGap(3, 3, 3)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jtf_apep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jtf_apem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lo_nombre)
                        .addComponent(jLabel2)
                        .addComponent(lo_apep)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))))
            .addGap(6, 6, 6)
            .addComponent(le_telefono)
            .addGap(5, 5, 5)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jLabel5))
                .addComponent(dateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jLabel6))
                .addComponent(jtf_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jLabel8))
                .addComponent(comboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jLabel7))
                .addComponent(jtf_dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(le_cedPro)
            .addGap(6, 6, 6)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboEspe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(lo_cedPro)
                .addComponent(jLabel10)
                .addComponent(jtf_cedPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jtf_usu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lo_pas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jtf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(comboAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lo_usu)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12)
                        .addComponent(jLabel1))))
            .addGap(35, 35, 35)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(BtnLimpiar)
                .addComponent(BtnGuardar)))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        limpiarCampos();
        limpiarLeyendasError();
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void jtf_telKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_telKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if (Character.isLetter(c)){
            getToolkit().beep();
            evt.consume();
            le_telefono.setVisible(true);
            BtnGuardar.enable(false);
        }else{
            le_telefono.setVisible(false);
            BtnGuardar.enable(true);
        }
    }//GEN-LAST:event_jtf_telKeyPressed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        // TODO add your handling code here:
        nombre=jtf_nombre.getText();
        apeP=jtf_apep.getText();
        apeM=jtf_apem.getText();
        f_nac=dateCombo.getText();//01/10/1999
        if (f_nac.length()<=9)
            f_nac="0"+f_nac;
        f_nac=f_nac.substring(6,10)+f_nac.substring(2,6)+f_nac.substring(0,2);
        tel=jtf_tel.getText();
        dir=jtf_dir.getText();
        sexo=comboSexo.getSelectedItem().toString();
        espe=comboEspe.getSelectedItem().toString();
        if (jtf_cedPro.getText().length()>0){
            cedula_prof=Integer.parseInt(jtf_cedPro.getText());
        }else{
            cedula_prof=0;
        }
        usuario=jtf_pass.getText();
        password=jtf_usu.getText();
        if (comboAdmin.getSelectedIndex()==0)
            admin="Usuario";
        else
            admin="Administrador";

        if (validarContenidoCampos()){
            String estatus="";
            med_adm.cargarInfoMedico(nombre,apeP,apeM,f_nac,tel,dir,sexo,espe,cedula_prof,usuario,password,admin);
            estatus=med_adm.insertNuevoMedico();
            if (estatus.equals("OK")){
                JOptionPane.showMessageDialog(null, "El medico fue registrado exitosamente.", "Registrar Medico.", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "El medico NO fue registrado exitosamente.\n\tERROR:"+estatus+".", "Registrar Medico.", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Ciertos campos no deben estar vacios, verifique.", "ALERTA",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void jtf_nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_nombreKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if (Character.isDigit(c)){
            getToolkit().beep();
            evt.consume();
            le_nombre.setVisible(true);
            BtnGuardar.setEnabled(false);
        }else{
            le_nombre.setVisible(false);
            BtnGuardar.setEnabled(true);
        }
        if (jtf_nombre.getText().length()==0){
            lo_nombre.setVisible(true);
            BtnGuardar.enable(false);
        }else{
            lo_nombre.setVisible(false);
            BtnGuardar.enable(true);
        }
    }//GEN-LAST:event_jtf_nombreKeyPressed

    private void jtf_apepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_apepKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if (Character.isDigit(c)){
            getToolkit().beep();
            evt.consume();
            le_apep.setVisible(true);
            BtnGuardar.enable(false);
        }else{
            le_apep.setVisible(false);
            BtnGuardar.enable(true);
        }
    }//GEN-LAST:event_jtf_apepKeyPressed

    private void jtf_apemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_apemKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if (Character.isDigit(c)){
            getToolkit().beep();
            evt.consume();
            le_apem.setVisible(true);
            BtnGuardar.enable(false);
        }else{
            le_apem.setVisible(false);
            BtnGuardar.enable(true);
        }
    }//GEN-LAST:event_jtf_apemKeyPressed

    private void jtf_cedProKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_cedProKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if (Character.isLetter(c)){
            getToolkit().beep();
            evt.consume();
            le_cedPro.setVisible(true);
            BtnGuardar.enable(false);
        }else{
            le_cedPro.setVisible(false);
            BtnGuardar.enable(true);
        }
    }//GEN-LAST:event_jtf_cedProKeyPressed
private void limpiarCampos(){
        jtf_nombre.setText("");
        jtf_apep.setText("");
        jtf_apem.setText("");
        jtf_tel.setText("");
        jtf_dir.setText("");
        jtf_pass.setText("");
        jtf_cedPro.setText("");
        jtf_usu.setText("");
        comboSexo.setSelectedIndex(0);
        comboEspe.setSelectedIndex(0);
        comboAdmin.setSelectedIndex(0);
        Calendar c= Calendar.getInstance();
         try {
             dateCombo.setDefaultPeriods(
                     new datechooser.model.multiple.PeriodSet(
                             new datechooser.model.multiple.Period(
                                     new java.util.GregorianCalendar(c.get(Calendar.YEAR), (c.get(Calendar.MONTH)+1), c.get(Calendar.DAY_OF_MONTH)),
                                     new java.util.GregorianCalendar(c.get(Calendar.YEAR), (c.get(Calendar.MONTH)+1), c.get(Calendar.DAY_OF_MONTH)))));
         } catch (IncompatibleDataExeption ex) {
             Logger.getLogger(NuevoMedico.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
    private void limpiarLeyendasError(){
        le_apem.setVisible(false);
        le_apep.setVisible(false);
        le_cedPro.setVisible(false);
        le_nombre.setVisible(false);
        le_telefono.setVisible(false);
        lo_apep.setVisible(false);
        lo_cedPro.setVisible(false);
        lo_nombre.setVisible(false);
        lo_pas.setVisible(false);
        lo_usu.setVisible(false);
    }
    private boolean validarContenidoCampos(){
        boolean respuesta=true;
        if (nombre.length()==0){
            lo_nombre.setVisible(true);
            BtnGuardar.setEnabled(false);
            respuesta=false;
        }
        if (apeP.length()==0){
            lo_apep.setVisible(true);
            BtnGuardar.setEnabled(false);
            respuesta=false;
        }
        if (usuario.length()==0){        
            lo_usu.setVisible(true);
            BtnGuardar.setEnabled(false);
            respuesta=false;
        }
        if (password.length()==0){        
            lo_pas.setVisible(true);
            BtnGuardar.setEnabled(false);
            respuesta=false;
        }
        if (cedula_prof==0){
            lo_cedPro.setVisible(true);
            BtnGuardar.setEnabled(false);
            respuesta=false;
        }
        return respuesta;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevoMedico dialog = new NuevoMedico(new javax.swing.JFrame(), true,new MedicoAdministrador());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JLabel Titulo;
    private javax.swing.JComboBox<String> comboAdmin;
    private javax.swing.JComboBox<String> comboEspe;
    private javax.swing.JComboBox<String> comboSexo;
    private datechooser.beans.DateChooserCombo dateCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jtf_apem;
    private javax.swing.JTextField jtf_apep;
    private javax.swing.JTextField jtf_cedPro;
    private javax.swing.JTextField jtf_dir;
    private javax.swing.JTextField jtf_nombre;
    private javax.swing.JTextField jtf_pass;
    private javax.swing.JTextField jtf_tel;
    private javax.swing.JTextField jtf_usu;
    private javax.swing.JLabel le_apem;
    private javax.swing.JLabel le_apep;
    private javax.swing.JLabel le_cedPro;
    private javax.swing.JLabel le_nombre;
    private javax.swing.JLabel le_telefono;
    private javax.swing.JLabel lo_apep;
    private javax.swing.JLabel lo_cedPro;
    private javax.swing.JLabel lo_nombre;
    private javax.swing.JLabel lo_pas;
    private javax.swing.JLabel lo_usu;
    // End of variables declaration//GEN-END:variables
}
