/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Beans.Imagen;
import Beans.MedicoBean;
import Beans.Paciente;
import Beans.Sesion;
import Clases.CapturadorImagen;
import Clases.ConsultaMedica;
import Clases.ServicioRespuesta;
import UpperEssential.UpperEssentialLookAndFeel;
import java.awt.Frame;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author laloe
 */
public class RegistroConsulta extends javax.swing.JDialog {

    /**
     * Creates new form RegistroConsulta3
     */
    private ConsultaMedica consulta = null;
    private Paciente paciente = null;
    private MedicoBean medico;
    private DefaultListModel modelo = new DefaultListModel();
    private String ip;
    public RegistroConsulta(java.awt.Frame parent, boolean modal,MedicoBean m) {
        super(parent, modal);
        ip = JOptionPane.showInputDialog("Ingrese direccion IP: ");
        if(ip==null)
            ip="";
        initComponents();
        
        fecha.setText(new SimpleDateFormat("yyyy-MM-dd").format(new Date()));
        medico = m;
        consulta = new ConsultaMedica(medico);
        
            doctor.setText(medico.getNombre() + " " + medico.getApellidoPaterno() + " " + medico.getApellidoMaterno());
        
        consulta.obtenerSiguienteIdCosnulta();
        
        
        /*nombreP.setVisible(false);
         direcc.setVisible(false);
         sexo.setVisible(false);
         sangre.setVisible(false);
         fechanac.setVisible(false);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
       @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        capturador1 = new CapturadorImagen(ip);
        capturador2 = new CapturadorImagen(ip);
        fecha = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        motivo = new javax.swing.JTextArea();
        doctor = new javax.swing.JTextField();
        idPaciente = new javax.swing.JTextField();
        consultaPaciente = new javax.swing.JButton();
        nombreP = new javax.swing.JTextField();
        fechanac = new javax.swing.JTextField();
        sexo = new javax.swing.JTextField();
        direcc = new javax.swing.JTextField();
        sangre = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        manifestacion = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        registrar = new javax.swing.JButton();
        captura1 = new javax.swing.JButton();
        captura2 = new javax.swing.JButton();
        receta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout capturador1Layout = new javax.swing.GroupLayout(capturador1);
        capturador1.setLayout(capturador1Layout);
        capturador1Layout.setHorizontalGroup(
            capturador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );
        capturador1Layout.setVerticalGroup(
            capturador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout capturador2Layout = new javax.swing.GroupLayout(capturador2);
        capturador2.setLayout(capturador2Layout);
        capturador2Layout.setHorizontalGroup(
            capturador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );
        capturador2Layout.setVerticalGroup(
            capturador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );

        fecha.setEditable(false);
        fecha.setText("Fecha");

        motivo.setColumns(20);
        motivo.setRows(5);
        jScrollPane1.setViewportView(motivo);

        doctor.setEditable(false);
        doctor.setText("Dr.");

        consultaPaciente.setText("Consultar");
        consultaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaPacienteActionPerformed(evt);
            }
        });

        nombreP.setEditable(false);
        nombreP.setName(""); // NOI18N
        nombreP.setOpaque(false);

        fechanac.setEditable(false);
        fechanac.setName(""); // NOI18N

        sexo.setEditable(false);
        sexo.setName(""); // NOI18N

        direcc.setEditable(false);
        direcc.setName(""); // NOI18N

        sangre.setEditable(false);
        sangre.setName(""); // NOI18N

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setEnabled(false);
        jScrollPane2.setViewportView(jList1);

        jButton1.setLabel("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });

        captura1.setText("Capturar");
        captura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                captura1ActionPerformed(evt);
            }
        });

        captura2.setText("Capturar");
        captura2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                captura2ActionPerformed(evt);
            }
        });

        receta.setText("Crear Receta");
        receta.setEnabled(false);
        receta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recetaActionPerformed(evt);
            }
        });

        jLabel1.setText("Doctor:");

        jLabel2.setText("Fecha:");

        jLabel3.setText("id del Paciente:");

        jLabel4.setText("Nombre del Paciente:");

        jLabel5.setText("Fecha de Nacimiento:");

        jLabel6.setText("Género:");

        jLabel7.setText("Tipo de Sangre:");

        jLabel8.setText("Dirección:");

        jLabel9.setText("Motivo de la Consulta:");

        jLabel10.setText("Manifestación");

        jLabel11.setText("Manifestaciones:");

        jLabel12.setText("Imagen del Ojo Derecho");

        jLabel13.setText("Imagen del Ojo Izquierdo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(registrar)
                        .addGap(55, 55, 55)
                        .addComponent(receta)
                        .addGap(569, 569, 569))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(consultaPaciente))
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(nombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(fechanac, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(14, 14, 14)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(sangre, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel7))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                                .addComponent(jLabel2)
                                                .addGap(28, 28, 28)
                                                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel9))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(manifestacion)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButton1))
                                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel10)
                                                            .addComponent(jLabel11))
                                                        .addGap(0, 0, Short.MAX_VALUE)))))
                                        .addGap(85, 85, 85)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(capturador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(capturador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel12)))
                                .addGap(43, 43, 43))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(direcc, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(204, 204, 204)
                                        .addComponent(jLabel13)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(captura1)
                            .addComponent(captura2))
                        .addGap(53, 53, 53))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(capturador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(capturador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(consultaPaciente))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fechanac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(direcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(manifestacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11)
                                        .addGap(5, 5, 5)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(captura1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(captura2)
                                .addGap(60, 60, 60)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(receta)
                    .addComponent(registrar))
                .addGap(26, 26, 26))
        );

        fecha.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>   

    private void consultaPacienteActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        ServicioRespuesta respuesta = consulta.validarPaciente(idPaciente.getText());
        if (respuesta.isSuccess()) {
            Paciente p = (Paciente) respuesta.getResult();
            nombreP.setVisible(true);
            direcc.setVisible(true);
            sexo.setVisible(true);
            sangre.setVisible(true);
            fechanac.setVisible(true);
            nombreP.setText(p.getNombre() + " " + p.getApellidoPaterno() + " " + p.getApellidoMaterno());
            direcc.setText(p.getDireccion());
            sexo.setText(p.getSexo());
            sangre.setText(p.getTipoSangre());
            fechanac.setText(new SimpleDateFormat("yyyy-MM-dd").format(p.getFechaNacimiento()));            
            //fechanac.setText(p.getFechaNacimiento());            
        } else {
            JOptionPane.showMessageDialog(null, "Paciente No Existe:\n"
                    + "Por favor ingrese un Paciente valido", "Paciente No Encontrado",
                    JOptionPane.ERROR_MESSAGE);
        }
        if(!ip.equals(""))
            capturador1.iniciar();
        
    }                                                

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        modelo.addElement(manifestacion.getText());
        jList1.setModel(modelo);
        manifestacion.setText("");
        
    }                                        

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        boolean respuesta=consulta.Registrar(motivo.getText(),modelo,new Imagen(capturador1.getImagen()),new Imagen(capturador2.getImagen()));
        if(respuesta==true){
            JOptionPane.showMessageDialog(null, "Registro de la Consulta exitoso", "Registro Completado",
                    JOptionPane.INFORMATION_MESSAGE);
            receta.setEnabled(true);
        }
    }                                         

    private void captura1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        capturador1.capturar();
        int ax = JOptionPane.showConfirmDialog(null, "¿Desea realizar otra captura?");
        System.out.println(ax);
        if(ax == JOptionPane.YES_OPTION){
            //JOptionPane.showMessageDialog(null, "Has seleccionado SI.");
            if(!ip.equals(""))
                capturador1.iniciar();
            else
                capturador1.removeAll();
        }
        else if(ax == JOptionPane.NO_OPTION||ax==2){
            captura1.setEnabled(false);
            if(!ip.equals(""))
                capturador2.iniciar();
        }
            //JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
            
    }                                        

    private void captura2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        capturador2.capturar();
        int ax = JOptionPane.showConfirmDialog(null, "¿Desea realizar otra captura?");
        System.out.println(ax);
        if(ax == JOptionPane.YES_OPTION)
            //JOptionPane.showMessageDialog(null, "Has seleccionado SI.");
            if(!ip.equals(""))
                capturador2.iniciar();
            else
                capturador2.removeAll();
        else if(ax == JOptionPane.NO_OPTION||ax==2)
            captura2.setEnabled(false);
            //JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
            
    }                                        
private void recetaActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    this.setVisible(false);
    consulta.CrearReceta(this);
    this.setVisible(true);
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /*try {
            UIManager.setLookAndFeel(new UpperEssentialLookAndFeel("C:\\Users\\laloe\\Documents\\TT\\librerias_SDTPO\\Chocolate.theme"));
        } catch (UnsupportedLookAndFeelException e) {

        }*/
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MedicoBean m = new MedicoBean();
                m.setCedulaPrfesional(2013630337);
//                new RegistroConsulta(m).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton captura1;
    private javax.swing.JButton captura2;
    private CapturadorImagen capturador1;
    private CapturadorImagen capturador2;
    private javax.swing.JButton consultaPaciente;
    private javax.swing.JTextField direcc;
    private javax.swing.JTextField doctor;
    private javax.swing.JTextField fecha;
    private javax.swing.JTextField fechanac;
    private javax.swing.JTextField idPaciente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField manifestacion;
    private javax.swing.JTextArea motivo;
    private javax.swing.JTextField nombreP;
    private javax.swing.JButton receta;
    private javax.swing.JButton registrar;
    private javax.swing.JTextField sangre;
    private javax.swing.JTextField sexo;
    // End of variables declaration                   
}
