/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Beans.Medicamento;
import Clases.RecetaMedica;
import Clases.ServicioRespuesta;
import java.awt.GridLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laloe
 */
public class RegistroReceta extends javax.swing.JDialog {
RecetaMedica receta = null;
    List<Medicamento> listaMedicamentos = null;
    ArrayList<Medicamento> listaMedicamentosSel;
    Vector columnas = null;
    boolean completado=false;
    /**
     * Creates new form RecetaMedica2
     */
    public RegistroReceta(java.awt.Frame parent, boolean modal, int idConsulta) {
        super(parent, modal);
        initComponents();
        listaMedicamentosSel = new ArrayList<>();
        receta = new RecetaMedica(idConsulta);
        fecha.setText(new SimpleDateFormat("yyyy-MM-dd").format(new Date()));
        
        cargarMedicamentos();
        columnas = new Vector();
        columnas.add("Id");
        columnas.add("Nombre");
        columnas.add("Presentacion");
        columnas.add("dosis");
        llenarTabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        recomendaciones = new javax.swing.JTextPane();
        registrarReceta = new javax.swing.JButton();
        fecha = new javax.swing.JTextField();
        comboMedicamentos = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMedicamentos = new javax.swing.JTable();
        agregar = new javax.swing.JButton();
        nuevo = new javax.swing.JButton();
        dosis = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane2.setViewportView(recomendaciones);

        registrarReceta.setText("Registrar Receta");
        registrarReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarRecetaActionPerformed(evt);
            }
        });

        fecha.setEditable(false);

        comboMedicamentos.setToolTipText("");

        tablaMedicamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "idMedicamento", "Nombre", "Presentación", "Dosis"
            }
        ));
        tablaMedicamentos.setEnabled(false);
        jScrollPane1.setViewportView(tablaMedicamentos);

        agregar.setText("Agregar");
        agregar.setActionCommand("");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        nuevo.setText("Nuevo");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dosis)
                                    .addComponent(comboMedicamentos, 0, 101, Short.MAX_VALUE))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(49, 49, 49)
                                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(registrarReceta)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuevo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregar))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registrarReceta)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarRecetaActionPerformed
        boolean respuesta=receta.registrarReceta(recomendaciones.getText(),listaMedicamentosSel);
        if(respuesta==true){
            JOptionPane.showMessageDialog(null, "Registro de la Receta exitoso", "Registro Completado",
                JOptionPane.INFORMATION_MESSAGE);
            completado=true;
            this.dispose();
        }
    }//GEN-LAST:event_registrarRecetaActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        
        if (dosis.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingresar dosis para el medicamento seleccionado", "Dosis no introducida",
                JOptionPane.ERROR_MESSAGE);
        } else if (comboMedicamentos.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Seleccionar un Medicamento", "Medicamento no Seleccionado",
                JOptionPane.ERROR_MESSAGE);
        } else {
            Medicamento m = listaMedicamentos.get(comboMedicamentos.getSelectedIndex());
            Medicamento mnuevo = new Medicamento(m.getIdMedicamento(), m.getNombre(), m.getPresentacion(), dosis.getText());

            listaMedicamentosSel.add(mnuevo);
            llenarTabla();
            comboMedicamentos.setSelectedIndex(-1);
            dosis.setText("");
        }
    }//GEN-LAST:event_agregarActionPerformed
private void cargarMedicamentos() {
        comboMedicamentos.removeAllItems();
        ServicioRespuesta respuesta = receta.obtenerMedicamentos();
        if (respuesta.isSuccess()) {
            listaMedicamentos = (List) respuesta.getResult();
            for (Medicamento med : listaMedicamentos) {
                comboMedicamentos.addItem(med.getNombre());
            }
            comboMedicamentos.setSelectedIndex(-1);
        }
    }
private void llenarTabla() {
        DefaultTableModel datos = new DefaultTableModel();
        for (int i = 0; i < columnas.size(); i++) {
            datos.addColumn(columnas.get(i));
        }
        this.tablaMedicamentos.setModel(datos);
        for (Medicamento med : listaMedicamentosSel) {
            Vector vec = new Vector();
            vec.add(med.getIdMedicamento());
            vec.add(med.getNombre());
            vec.add(med.getPresentacion());
            vec.add(med.getDosis());
            datos.addRow(vec);
        }
    }
    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        // TODO add your handling code here:
        JPanel panel = new JPanel();
        JTextField nombre = new JTextField();
        JTextField presentacion = new JTextField();
        JLabel name=new JLabel("Nombre: ");
        JLabel present=new JLabel("Presentación: ");

        panel.setLayout(new GridLayout(2, 2));
        panel.add(name);
        panel.add(nombre);
        panel.add(present);
        panel.add(presentacion);
        int desicion=JOptionPane.showOptionDialog(null, panel,"Crear Medicamento", JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE, null, null, null);
        if(desicion==0){
            if(nombre.getText().equals("")&&presentacion.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Todos Los campos deben estar llenos ", "No se realizo el registro",
                    JOptionPane.ERROR_MESSAGE);
            }
            else{
                Medicamento medic=new Medicamento();
                medic.setNombre(nombre.getText());
                System.out.println(nombre.getText());
                medic.setPresentacion(presentacion.getText());
                System.out.println(presentacion.getText());
                ServicioRespuesta respuesta=receta.crearMedicamento(medic);
                if(respuesta.isSuccess()){
                JOptionPane.showMessageDialog(null, "El medicamento se registro exitosamente", "Registro Completado",
                    JOptionPane.INFORMATION_MESSAGE);}
                cargarMedicamentos();
            }
        }

    }//GEN-LAST:event_nuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistroReceta dialog = new RegistroReceta(new javax.swing.JFrame(), true,3);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JComboBox comboMedicamentos;
    private javax.swing.JTextField dosis;
    private javax.swing.JTextField fecha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton nuevo;
    private javax.swing.JTextPane recomendaciones;
    private javax.swing.JButton registrarReceta;
    private javax.swing.JTable tablaMedicamentos;
    // End of variables declaration//GEN-END:variables
}
